name: Go Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      uses: docker://krakend/builder:latest-linux-generic
      with:
        args: sh -c "go get -t -v ./...
         gofmt -w -s . && git diff --exit-code
         go tool vet .
         go test -v -race ./..."